export const APIRoutes = {
  reports: "reports",
  reportApps: "reportApps?",
  reportAppDetails: "reportAppDetails?",
  credentials: "credentials",
  organizations: "organizations",
  environments: "environments",
  certificates: "api/Certificate/GetAll",
  agencies: "agencies",
  errors: "errors-message",
  packages: "packages",
  signatureBoxs: "signatureBoxs",
  signature: "signature",
  editUser: "credentials",
  users: "users",
};
